odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

# 2017-06-06: wxm added to avoid lag, doesnt work though
#use_control: true # listens to /cmd_vel and will use it in state prediction to avoid lag
#control_config: [true,  false, false, # xdot ydot zdot
#                 false, false, true]  # rolldot pitchdot yawdot

frequency: 50

odom0: husky_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false, # tom moore defaulted to this 2 years ago #true, false, false,    # x y z velocities
               false, false, true,    # yaw velocity
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: imu/data
# 2016-12-05: wxm removed position estimate from IMU as recommended by CRL support
#imu0_config: [false, false, false,
#              true, true, true,
#              false, false, false,
#              true, true, true,
#              false, false, false]
imu0_config: [false, false, false,
                false, false, false,
                false, false, false,
                false, false, true,
                true, true, false]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
