sensors:
    - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
      point_cloud_topic: /xtion/depth/points
      queue_size: 2
      near_clipping_plane_distance: 0.3
      far_clipping_plane_distance: 5.0
      shadow_threshold: 0.2
      padding_scale: 4.0
      padding_offset: 0.03
      filtered_cloud_topic: filtered_cloud
